---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6

suites:
  - name: downloader
    run_list:
      - recipe[chef-cookbook-wordpress::downloader]
    attributes:
      wordpress:
        downloader:
          destination: "./mydownloadfolder/"
  - name: installer
    provision_command:
      - groupadd vagrant
      - useradd vagrant
    run_list:
      - recipe[chef-cookbook-wordpress::downloader]
      - recipe[chef-cookbook-wordpress::installer]
    attributes:
      wordpress:
        downloader:
          destination: "/mydownloadfolder/"
        installer:
          extraction_destination: "/mydownloadfolder/myextractionfolder"
          extraction_destination_dir_owner: 'vagrant'
          extraction_destination_dir_group: 'vagrant'
          wp_config_file_mode: "0777"
          wp_config_file_group: vagrant
          wp_config_file_owner: vagrant
          wp_config:
            db_name: 'mydbname'
            db_user: 'mydbuser'
            db_password: 'mydbpassword'
            db_host: 'mydbhostname'
            db_charset: 'mydbcharset'
            db_collate: 'mydbcollate'
            auth_key: 'myauthkey'
            secure_auth_key: 'mysecureauthkey'
            logged_in_key: 'myloggedinkey'
            nonce_key: 'mynoncekey'
            auth_salt: 'myauthsalt'
            secure_auth_salt: 'mysecureauthsalt'
            logged_in_salt: 'myloggedinsalt'
            nonce_salt: 'mynoncesalt'
            table_prefix: 'mytableprefix_'
            wp_debug: true
            additional_config_params:
              param1: "'myparamstring'"
              param2: true
              param3: 123
              param4: 123.123
