build:
  tests:
    before:
      - echo 'Pulling docker init script from zuazo/kitchen-in-travis on GitHub'
      - source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.1.0/scripts/start_docker.sh)
      -
        command: echo 'Setting up test environment variable'
        environment: { TRAVIS: 'true' }
        background: false
    override:
      - bundle exec rake integration:docker
  environment:
    ruby: '2.2.0'
checks:
  ruby: true
filter:
  excluded_paths:
    - templates/*
    - test/*
    - spec/*
