language: ruby
rvm:
  - 2.2.0
before_install:
  - sudo sh -c "echo 'deb http://download.virtualbox.org/virtualbox/debian '$(lsb_release -cs)' contrib non-free' > /etc/apt/sources.list.d/virtualbox.list" && wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get -y --fix-missing install dkms
  - sudo apt-get -y --fix-missing install build-essential
  - sudo apt-get -y --fix-missing install linux-headers-generic
  - sudo apt-get -y --fix-missing install virtualbox
  - sudo apt-get -y --fix-missing install virtualbox-qt
  - sudo apt-get -y --fix-missing install virtualbox-dkms
  - sudo apt-get -y --fix-missing install virtualbox-guest-dkms
  - sudo apt-get -y --fix-missing install virtualbox-ose-dkms
  - VBoxManage --version
matrix:
  fast_finish: true
