language: ruby
rvm:
  - 2.2.0
before_install:
  - sudo apt-get -y install aptitude
  - sudo aptitude update
  - sudo aptitude -y upgrade
  - sudo aptitude install linux-image-extra-`uname -r`
  - sudo sh -c "wget -qO- https://get.docker.io/gpg | apt-key add -"
  - sudo sh -c "echo deb http://get.docker.io/ubuntu docker main /etc/apt/sources.list.d/docker.list
  - sudo aptitude update
  - sudo aptitude install lxc-docker
matrix:
  fast_finish: true
