language: ruby
rvm:
  - 2.2.0
before_install:
  - sudo apt-get -y update
  - sudo apt-get -y --fix-missing
  - sudo apt-get -y install linux-headers-generic
  - sudo sh -c "echo 'deb http://download.virtualbox.org/virtualbox/4.3.28/virtualbox-4.3_4.3.28-100309~Ubuntu~precise_i386.deb' > /etc/apt/sources.list.d/virtualbox.list" && wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get -y install virtualbox virtualbox-qt virtualbox-dkms virtualbox-guest-dkms virtualbox-ose-dkms
  - VBoxManage --version
matrix:
  fast_finish: true
