rvm:
  - 2.2.0

sudo: true

before_script:
  - source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.1.0/scripts/start_docker.sh)

script:
  - bundle exec rake integration:docker
